### ISSUE TITLE
wavenumber definition

### ISSUE THREAD

**Issue by 9com** [NelisW/pyradi#21]
It seems I am mis-interpreting Pyradi's definition of wavenumber.
 the Pyradi manual shows that a wavenumber of 3300cm^-1 equals a wavelegnth = 3um.    Does this means that Pyradi uses wavelegnth=1/wavenumber ?  Of course we know that frequency = 1/wavenumber    and that wavelegnth= 2*PI()/wavenumber.   
Also, in  the module " ryutils.convertSpectralDomain "  the wavenumber range seems to be limited from 2000cm^-1   to   3300cm^-1.  Is this true ?
Reference:    waven = np.arange(2000.0,  3300.0,  50).reshape(-1, 1)
                    wavel= ryutils.convertSpectralDomain(waven,  type='nl')      Thank you !!

**Comment by sfcook526** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by 9com** [comment]
Thanks for your fast response.

If wavelegnth = 1.55um then Waven = 6451.61 cm-1 ,    Heres a wave number range:  waven = np.arange(4500,  6500,  25).reshape(-1, 1)  that would be required.
I get:   ValueError: A value in x_new is above the interpolation range.
How can we use :   waven = np.arange(4500,  6500,  25).reshape(-1, 1)

Thank you

**Comment by NelisW** [comment]
Thanks guys for the interest and response.

Indeed (wavenumber in cm-1)*(wavelength in um) = 10 000.
There is no enforced limit on the values, except to standard numerical over/underflow, etc.

Your issue is a Python issue, not a pyradi issue. 
I don't use arange, normally use np.linspace.
Without a https://en.wikipedia.org/wiki/Minimal_working_example I cannot really comment on your problem.
